services:
  db:
    image: mariadb:10
    volumes:
      - ./db/certs:/certs:ro
      - ./db/db.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306"
    env_file:
      - path: ./local.env
        required: false

  app:
    build: ./
    volumes:
      - ./app:/app
      - ./auth.json:/root/.composer/auth.json
    ports:
      - "51140:80"
      - "51143:443"
    mem_limit: 200m
    depends_on:
      - db
    env_file:
      - path: ./local.env
        required: false
      - ./db/certs/test.env
    environment:
      #            RUN_TASK: cron/all
      EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
      EMAIL_SIGNATURE: "Dummy Signature for Development\r\rdo not reply to this email"

  appfortests:
    build: ./
    volumes:
      - ./app:/app
      - ./auth.json:/root/.composer/auth.json
    mem_limit: 200m
    ports:
      - "80"
    depends_on:
      - testdb
    env_file:
      - ./db/certs/test.env
      - ./test.env

  testdb:
    image: mariadb:10
    volumes:
      - ./db/certs:/certs:ro
      - ./db/testdb.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss!
      MYSQL_DATABASE: appfortests
      MYSQL_USER: appfortests
      MYSQL_PASSWORD: appfortests

  cli:
    image: ghcr.io/sil-org/php8:8.3
    platform: linux/amd64
    volumes:
      - composer-cache:/composer
      - ./app:/app
      - ./auth.json:/root/.composer/auth.json
    working_dir: /app
    environment:
      COMPOSER_CACHE_DIR: /composer
    env_file:
      - path: ./local.env
        required: false
    command: ["true"]

  dynamo:
    image: amazon/dynamodb-local
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abc123
      AWS_DEFAULT_REGION: us-east-1
    command: "-jar DynamoDBLocal.jar -sharedDb"

  mfaapi:
    build: ./serverless-mfa-api
    ports:
      - 8080
    volumes:
      - ./serverless-mfa-api/override:/src/override
    environment:
      AWS_ENDPOINT: http://dynamo:8000
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abc123
      AWS_DISABLE_SSL: "true"
      API_KEY_TABLE: ApiKey
      TOTP_TABLE: Totp
      WEBAUTHN_TABLE: WebAuthn
    depends_on:
      - dynamo
      - dynamorestart
    working_dir: /src
    # Copy files from the override folder to be used for possible troubleshooting (e.g. with extra log statements)
    # (using bash -c to keep the chown command from ignoring the && and throwing an error)
    command: bash -c "cp -R ./override/* ./ && go run ./server/"

  u2fsim:
    build: ./u2f-simulator
    ports:
      - 8080
    volumes:
      - ./u2f-simulator/override:/src/override
    working_dir: /src
    # Copy files from the override folder to be used for possible troubleshooting (e.g. with extra log statements)
    command: bash -c "cp -R ./override/* ./ && go run ./u2fserver/"

  dynamorestart:
    build: ./dynamorestart
    ports:
      - 8080
    volumes:
      - ./dynamorestart/:/dynamo
    environment:
      AWS_ENDPOINT: dynamo:8000
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abc123
      AWS_DISABLE_SSL: "true"
      API_KEY_TABLE: ApiKey
      WEBAUTHN_TABLE: WebAuthn
    depends_on:
      - dynamo
    working_dir: /dynamo
    command: bash -c "pwd && ls -al && php restart.php"

  test:
    image: ghcr.io/sil-org/php8:8.3
    platform: linux/amd64
    volumes:
      - ./app:/app
      - ./auth.json:/root/.composer/auth.json
    mem_limit: 200m
    working_dir: /app
    depends_on:
      - appfortests
      - mfaapi
      - u2fsim
    env_file:
      - ./db/certs/test.env
      - ./test.env
    command: ./run-tests.sh
    # running isolated tests
    # docker compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature
    # docker compose run --rm test vendor/bin/behat --stop-on-failure features/user.feature:306

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - "51141:80"
    depends_on:
      - db
    env_file:
      - path: ./local.env
        required: false
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass
      PMA_SSL: 1

  phpmyadmintest:
    image: phpmyadmin:5
    ports:
      - "51142:80"
    depends_on:
      - testdb
    env_file:
      - path: ./local.env
        required: false
    environment:
      PMA_HOST: testdb
      PMA_USER: appfortests
      PMA_PASSWORD: appfortests
      PMA_SSL: 1

  raml2html:
    image: mattjtodd/raml2html
    platform: linux/amd64
    volumes:
      - ./api.raml:/api.raml
      - ./api.html:/api.html
    # The ENTRYPOINT in the Dockerfile is "raml2html"
    command: -i api.raml -o api.html

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.39.0/24
          gateway: 10.20.39.1

volumes:
  composer-cache:
